#ifndef ACA_PROJECT_SIMD_DEFS_H
#define ACA_PROJECT_SIMD_DEFS_H

#define SIMD_WIDTH_SSE2 16
#define SIMD_WIDTH_AVX2 32
#define SIMD_WIDTH_AVX512F 64
#define DEFAULT_BLOCK_WIDTH -1

#endif //ACA_PROJECT_SIMD_DEFS_H
